keycloak:
  enabled: true
  realm: astron-realm
  auth-server-url: http://localhost:8080
  ssl-required: EXTERNAL #기본값은 외부 요청에 HTTPS가 기본적으로 필요하다는 외부 의미 유효한 값은 'ALL', 'EXTERNAL', 'NONE'
  resource: astron-client
  credentials:
    secret: noDeIPTnvwXbMgHU2ZEopoQVBuCBimgo
  use-resource-role-mappings: true
  bearer-only: true

server:
  port: 8081