keycloak:
  enabled: true
  realm: hello-realm
  auth-server-url: http://localhost:8080
  ssl-required: EXTERNAL #기본값은 외부 요청에 HTTPS가 기본적으로 필요하다는 외부 의미 유효한 값은 'ALL', 'EXTERNAL', 'NONE'
  resource: hello-client
  credentials:
    secret: AD22aVZUgWXipSAT4EsuL1D8Ju3zc0Zp
  use-resource-role-mappings: true
  bearer-only: true

server:
  port: 8081